# Generated by Django 4.0.6 on 2022-07-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('parentezco', models.CharField(max_length=40)),
                ('edad', models.IntegerField(max_length=40)),
                ('fechaDeNacimiento', models.DateField(max_length=40)),
                ('trabajador', models.BooleanField()),
            ],
        ),
    ]
