# Generated by Django 4.0.6 on 2022-07-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='fechaDeNacimiento',
            field=models.DateField(),
        ),
    ]
